provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "aks_rg" {
  name     = "AzureResource3"
  location = "South Central US"
}

resource "azurerm_kubernetes_cluster" "aks_cluster" {
  name                = "myterraform"
  location            = azurerm_resource_group.aks_rg.location
  resource_group_name = azurerm_resource_group.aks_rg.name
  dns_prefix          = "myaks"

  default_node_pool {
    name       = "default"
    node_count = 2
    vm_size    = "Standard_B2ms"
  }
  service_principal {
    client_id     = "90c99150-9f70-4ac3-b229-e66c6bed3090"
    client_secret = "7I18Q~dpagh5R3amSxO88q8CIKN3w9H7a7cMKaVq"
  }

  tags = {
    environment = "development"
  }
}

resource "azurerm_storage_account" "storage_account" {
  name                     = "bhupathi"
  resource_group_name      = azurerm_resource_group.aks_rg.name
  location                 = azurerm_resource_group.aks_rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"

  tags = {
    environment = "development"
  }
}